### ISSUE TITLE
No clear information about original library

### ISSUE THREAD

**Issue by tarlepp** [systemsdk/easy-log-bundle#1]
I think that this repository should tell clearly that the original repository of this is https://github.com/EasyCorp/easy-log-handler - imho readme.md should at least contain link to that original repository.

Seems like readme.md contains "Forked from EasyCorp/easy-log-handler" - but this repository itself _is not_ a fork of that repository - so that will mislead people - imho.

**Comment by dimadeush** [comment]
Hello. Done, thanks.

**Comment by tarlepp** [comment]
Seems to be solved - but really I would recommend you to use PR's to fix things like this one - then you could just add this issue to your PR description and people would actually see easily what has been updated.
